version: "3"
services:
  rest-flask-app:
    build: .
    environment: 
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    volumes: 
      - "./:/app"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: agusrichard
      MYSQL_USER: agusrichard
      MYSQL_PASSWORD: agusrichard
      MYSQL_DATABASE: rest_flask_app_db
    ports:
      - "3308:3306"