version: "3.1"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - service-one
  service-one:
    build:
      context: ./
      dockerfile: ./service_one/Dockerfile
    container_name: flask-service-one
    command: flask run --host=0.0.0.0 --port=3000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=./service_one/main.py
    ports:
      - 3000:3000
    volumes:
      - ./:/app/service_one
    networks:
      my-network:
        aliases:
          - flask-app-network
  service-two:
    build:
      context: ./
      dockerfile: ./service_two/Dockerfile
    container_name: flask-service-two
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=./service_two/main.py
    ports:
      - 5000:5000
    volumes:
      - ./:/app/service_two
    networks:
      my-network:
        aliases:
          - flask-app-network

networks:
  my-network:
